### ISSUE TITLE
Add app icon

### ISSUE THREAD

**Issue by ErikBoesen** [ErikBoesen/wristcoach#1]

**Comment by darkroastcreative** [comment]
Can you provide details for what you would like, and the desired specs for the icon? Specifically, what visual direction do you want to take, and where will the icon be used?

**Comment by ErikBoesen** [comment]
@caffeineandfoxes I will just be making a small icon for the app in the Pebble app list. Not really a high priority issue right now.

**Comment by ErikBoesen** [comment]
This does it:
https://github.com/sdneon/Enigma-plus/blob/master/appinfo.json
